### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by xiaofuyesnew** [taosishun/study#1]
- 如果更改了多文件，如何一次性将更改的文件添加进暂存区？

- 如果某次提交出现了错误，如何进行回退操作？

**Comment by taosishun** [comment]
git add txt1 txt2 txt3可以提交多个文件  回退git reset head Haed ^

**Comment by xiaofuyesnew** [comment]
@taosishun 

添加暂存区更简单的办法

```shell
git add .
```

`.`表示相对路径，即当前git命令作用的路径，如果你一次更改100,200个文件……

**Comment by taosishun** [comment]
还有git add all 只是我没试过

**Comment by xiaofuyesnew** [comment]
@taosishun 

关于暂存区你需要知道的三个参数

```shell
git add .        # 表示将新增和修改的文件加入暂存区（不包括删除的）

git add -u     # 表示将已经在暂存区的文件的更改和删除，加入到暂存区（不包括新增的）git add --update的简写

git add -A     # 表示上面两种情况的合集，是git add --all的简写
```
我问的修改文件，三者都可以，但为什么不用最简便的方式呢，对吧？

**Comment by taosishun** [comment]
@xiaofuyesnew git checkout 为什么又能切换，又能撤销，那git swtich 的意义在哪里

**Comment by xiaofuyesnew** [comment]
> @xiaofuyesnew git checkout 为什么又能切换，又能撤销，那git swtich 的意义在哪里

`git checkout`是通用的方式，带不同的参数可以实现不同的功能。

2.23版本以后，它被拆分成了`git switch`和`git restore`，根据习惯选择一个方向去用就好了。没有什么不同。
